  export const links = [
    { id: "01", href: "/latest", label: "সর্বশেষ" },
    { id: "02", href: "/national", label: "জাতীয়" },
    { id: "03", href: "/politics", label: "রাজনীতি" },
    { id: "04", href: "/countrywide", label: "সারাদেশ" },
    { id: "05", href: "/international", label: "বিশ্ব" },
    { id: "06", href: "/sports", label: "খেলা" },
    { id: "07", href: "/education", label: "শিক্ষা" },
    { id: "08", href: "/health", label: "স্বাস্থ্য" },
    { id: "09", href: "/opinion", label: "মতামত" },
    { id: "10", href: "/religion", label: "ধর্ম" },
    { id: "11", href: "/crime", label: "অপরাধ" },
    { id: "12", href: "/technology", label: "প্রযুক্তি" },
    { id: "13", href: "/entertainment", label: "বিনোদন" },
    { id: "14", href: "/economy", label: "অর্থনীতি" },
    { id: "15", href: "/law-and-justice", label: "আইন ও আদালত" },
    { id: "16", href: "/environment", label: "পরিবেশ" },
    { id: "17", href: "/science", label: "বিজ্ঞান" },
  ];