export const links = [
  { id: "01", href: "/latest", label: "সর্বশেষ" },
  { id: "02", href: "/national", label: "জাতীয়" },
  { id: "03", href: "/politics", label: "রাজনীতি" },
  { id: "04", href: "/countrywide", label: "সারাদেশ" },
  { id: "05", href: "/international", label: "আন্তর্জাতিক" },
  { id: "06", href: "/sports", label: "খেলা-দুলা" },
  { id: "07", href: "/education", label: "শিক্ষা" },
  { id: "08", href: "/health", label: "স্বাস্থ্য" },
  { id: "09", href: "/opinion", label: "মতামত" },
  { id: "10", href: "/religion", label: "ধর্ম" },
  { id: "11", href: "/crime", label: "ক্রাইম" },
  { id: "12", href: "/technology", label: "তথ্য প্রযুক্তি" },
  { id: "13", href: "/entertainment", label: "বিনোদন" },
  { id: "14", href: "/economy", label: "অর্থনীতি" },
  { id: "15", href: "/law-and-justice", label: "আইন ও আদালত" },
  { id: "16", href: "/environment", label: "পরিবেশ ও জলবায়ু" },
  { id: "17", href: "/science", label: "বিজ্ঞান ও গবেষণা" },
  { id: "18", href: "/war", label: "যুদ্ধ আপডেট" },

  { id: "19", href: "/travel", label: "ভ্রমণ" },
  { id: "20", href: "/weather", label: "দুর্যোগ ও আবহাওয়া" },
  { id: "21", href: "/recipe", label: "রেসিপি" },
  { id: "22", href: "/notice", label: "বিজ্ঞপ্তি" },
  { id: "23", href: "/farming", label: "কৃষি-গ্রাম বাংলা" },
  { id: "24", href: "/literature", label: "শিল্প ও সাহিত্য" },
  { id: "25", href: "/job", label: "চাকরি" },

  { id: "26", href: "/foreign", label: "প্রবাস" },
  { id: "27", href: "/lifestyle", label: "লাইফস্টাইল" },
  { id: "28", href: "/socialmedia", label: "সোশ্যাল মিডিয়া" },
  { id: "29", href: "/womenkids", label: "নারী ও শিশু" },
  { id: "30", href: "/elections", label: "নির্বাচন" },
  { id: "31", href: "/others", label: "অন্যান্য" },
  { id: "32", href: "/badnews", label: "দু-সংবাদ" },
  { id: "33", href: "/goodnews", label: "সু-সংবাদ" },
  { id: "34", href: "/procchod", label: "প্রচ্ছদ" },
];
